spring.cloud.stream:
  bindings:
    output:
      contentType: application/json
      destination: product-counts
      producer:
        headerMode: raw
        useNativeEncoding: true
    input:
      destination: products
      consumer:
        headerMode: raw
  kafka:
    binder.configuration.auto.offset.reset: earliest
    streams:
      binder:
        brokers: localhost
        zkNodes: localhost
        configuration:
          commit.interval.ms: 1000
        key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings.output.producer:
        keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
        valueSerde: org.apache.kafka.common.serialization.Serdes$LongSerde
spring.data.mongodb.uri: mongodb://localhost:27017/spring-flux
